vich_uploader:
  db_driver: orm

  mappings:
    servicesImg:
      uri_prefix: /assets/servicesImg
      upload_destination: "%kernel.project_dir%/public/assets/servicesImg"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
